[project]
name = "movies"
version = "0.1.0"
description = "Movies catalog"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi-cli>=0.0.8",
    "fastapi[standart]>=0.116.1",
    "python-multipart>=0.0.20",
]
